from sqlalchemy import (create_engine, Column, Integer, String, Text,
                        DateTime, Float, Boolean, ForeignKey, UniqueConstraint)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship
from sqlalchemy import inspect as sa_inspect, text
from datetime import datetime

SQLALCHEMY_DATABASE_URL = "sqlite:///./similarity.db"
engine = create_engine(SQLALCHEMY_DATABASE_URL,
                       connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


class User(Base):
    __tablename__ = "users"
    id              = Column(Integer, primary_key=True, index=True)
    name            = Column(String, nullable=False)
    email           = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    role            = Column(String, default="student")  # "admin", "teacher", "student"
    is_active       = Column(Boolean, default=True)
    created_at      = Column(DateTime, default=datetime.utcnow)


class TeacherAccessCode(Base):
    """Access codes generated by admin — teachers use them when registering."""
    __tablename__ = "teacher_access_codes"
    id         = Column(Integer, primary_key=True, index=True)
    code       = Column(String, unique=True, nullable=False)
    label      = Column(String, default="")
    created_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    used_by    = Column(Integer, ForeignKey("users.id"), nullable=True)
    is_used    = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)


class TeacherCourse(Base):
    """A (program, course_code) pair a teacher has registered to oversee."""
    __tablename__ = "teacher_courses"
    id          = Column(Integer, primary_key=True, index=True)
    teacher_id  = Column(Integer, ForeignKey("users.id"), nullable=False)
    program     = Column(String, nullable=False)
    course_code = Column(String, nullable=False)
    course_name = Column(String, default="")
    created_at  = Column(DateTime, default=datetime.utcnow)
    __table_args__ = (
        UniqueConstraint("teacher_id", "program", "course_code",
                         name="uq_teacher_course"),
    )
    teacher = relationship("User", foreign_keys=[teacher_id])


class Assignment(Base):
    """An assignment created by a teacher for a specific course."""
    __tablename__ = "assignments"
    id              = Column(Integer, primary_key=True, index=True)
    title           = Column(String, nullable=False)
    description     = Column(Text, default="")
    teacher_id      = Column(Integer, ForeignKey("users.id"), nullable=False)
    course_id       = Column(Integer, ForeignKey("teacher_courses.id"), nullable=False)
    due_date        = Column(DateTime, nullable=True)
    allowed_formats  = Column(String, default=".pdf,.docx,.txt")
    max_marks           = Column(Integer, default=100)
    grading_criteria    = Column(Text, default="")
    auto_grade_enabled  = Column(Boolean, default=False)
    is_active           = Column(Boolean, default=True)
    created_at       = Column(DateTime, default=datetime.utcnow)
    teacher  = relationship("User", foreign_keys=[teacher_id])
    course   = relationship("TeacherCourse", foreign_keys=[course_id])


class StudentEnrollment(Base):
    """Which students are enrolled in which courses — controlled by admin."""
    __tablename__ = "student_enrollments"
    id          = Column(Integer, primary_key=True, index=True)
    student_id  = Column(Integer, ForeignKey("users.id"), nullable=False)
    course_id   = Column(Integer, ForeignKey("teacher_courses.id"), nullable=False)
    enrolled_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    enrolled_at = Column(DateTime, default=datetime.utcnow)
    __table_args__ = (
        UniqueConstraint("student_id", "course_id", name="uq_enrollment"),
    )
    student = relationship("User", foreign_keys=[student_id])
    course  = relationship("TeacherCourse", foreign_keys=[course_id])


class Document(Base):
    __tablename__ = "documents"
    id            = Column(Integer, primary_key=True, index=True)
    filename      = Column(String, nullable=False)
    student_name  = Column(String, nullable=False)
    matric_no     = Column(String, nullable=False)
    program       = Column(String, nullable=False)
    course_code   = Column(String, nullable=False)
    teacher_id    = Column(Integer, ForeignKey("users.id"), nullable=False)
    owner_id      = Column(Integer, ForeignKey("users.id"), nullable=False)
    assignment_id  = Column(Integer, ForeignKey("assignments.id"), nullable=True)
    file_path      = Column(String, nullable=False)
    raw_text       = Column(Text)
    clean_text     = Column(Text)
    uploaded_at    = Column(DateTime, default=datetime.utcnow)
    marks          = Column(Float, nullable=True)
    grade_feedback = Column(Text, default="")
    graded_by      = Column(Integer, ForeignKey("users.id"), nullable=True)
    graded_at      = Column(DateTime, nullable=True)
    assignment     = relationship("Assignment", foreign_keys=[assignment_id])


class Feedback(Base):
    """One similarity finding sent from a teacher to a student."""
    __tablename__ = "feedback"
    id                 = Column(Integer, primary_key=True, index=True)
    recipient_id       = Column(Integer, ForeignKey("users.id"), nullable=False)
    teacher_id         = Column(Integer, ForeignKey("users.id"), nullable=False)
    document_id        = Column(Integer, ForeignKey("documents.id"), nullable=False)
    program            = Column(String, nullable=False)
    course_code        = Column(String, nullable=False)
    similar_to_name    = Column(String, nullable=False)
    similar_to_matric  = Column(String, nullable=False)
    similar_to_program = Column(String, nullable=False)
    percentage         = Column(Float, nullable=False)
    level              = Column(String, nullable=False)
    message            = Column(Text, default="")
    created_at         = Column(DateTime, default=datetime.utcnow)
    is_read            = Column(Boolean, default=False)


Base.metadata.create_all(bind=engine)


def _migrate():
    """Add columns that did not exist in older schema versions."""
    insp = sa_inspect(engine)
    migrations = [
        ("documents",      "assignment_id",  "INTEGER REFERENCES assignments(id)"),
        ("users",          "is_active",      "INTEGER DEFAULT 1"),
        ("teacher_courses","course_name",    "TEXT DEFAULT ''"),
        ("assignments",    "max_marks",      "INTEGER DEFAULT 100"),
        ("assignments",    "grading_criteria",   "TEXT DEFAULT ''"),
        ("assignments",    "auto_grade_enabled", "INTEGER DEFAULT 0"),
        ("documents",      "marks",          "REAL"),
        ("documents",      "grade_feedback", "TEXT DEFAULT ''"),
        ("documents",      "graded_by",      "INTEGER REFERENCES users(id)"),
        ("documents",      "graded_at",      "DATETIME"),
    ]
    for table, col, col_def in migrations:
        try:
            existing = [c["name"] for c in insp.get_columns(table)]
            if col not in existing:
                with engine.connect() as conn:
                    conn.execute(text(f"ALTER TABLE {table} ADD COLUMN {col} {col_def}"))
                    conn.commit()
        except Exception:
            pass


_migrate()


def seed_default_admin():
    """Ensure the default admin account exists (called on app startup)."""
    from app.auth import hash_password
    db = SessionLocal()
    try:
        if not db.query(User).filter(User.role == "admin").first():
            admin = User(
                name="System Administrator",
                email="admin@ase.edu",
                hashed_password=hash_password("Admin@2025"),
                role="admin",
            )
            db.add(admin)
            db.commit()
    finally:
        db.close()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
